### ISSUE TITLE
Prepare Release v2.0

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#327]
As #251 and #291 and all extracts are completed we are ready release v2.0.

Last steps:

- [x] Publish latest planet https://osm2vectortiles-downloads.os.zhdk.cloud.switch.ch/v2.0/planet.mbtiles to CDN
- [x] Update GitHub pages with #319 
- [x] https://github.com/osm2vectortiles/mapbox-gl-styles/commit/38dab34651ee05392900c8fd72ec2c83c985aace Tweak **Dark**, **Light**, **Streets** styles to show big cities (remove `ldir` filter)
- [ ] ~~Ensure #324 builds and merge it since it is part of the released vector tiles~~
- [x] Ensure correct metadata on planet files so that #247 does not happen again
- [x] 1ab9ac9ad145314d2e1daaa5ed0ce85734d6a74e Add copy link field for planet.mbtiles
- [x] Release GitHub milestone
- [ ] ~~Ensure Docker containers match the versions~~

![map_styles_ _osm2vectortiles](https://cloud.githubusercontent.com/assets/1288339/15463224/254eddc4-20c8-11e6-9908-4a772a990d96.png)

![cursor_and_downloads_ _osm2vectortiles](https://cloud.githubusercontent.com/assets/1288339/15463017/d411f140-20c6-11e6-9ac9-d282e228166b.png)

**Comment by klokan** [comment]
V2 deployed at http://osm2vectortiles.tileserver.com/

There are issues with the new planet MBTiles - missing bounds (!) + metadata contains SQL(!?) + name mentions version 1.4 not 2.

**Comment by lukasmartinelli** [comment]
> There are issues with the new planet MBTiles - missing bounds (!) + metadata contains SQL(!?) + name mentions version 1.4 not 2.

The SQL is weird but it still valid. Tilelive-copy and tl copy now add the tm2source content to the MBTiles metadata as well.

I corrected the planet MBTiles and reuploaded.

```sql
UPDATE metadata SET value='tms' WHERE name='scheme';
UPDATE metadata SET value='pbf' WHERE name='format';
UPDATE metadata SET value='<a href="http://www.openstreetmap.org/about/" target="_blank">&copy; OpenStreetMap contributors</a>' WHERE name='attribution';
UPDATE metadata SET value='Free vector tiles from from http://osm2vectortiles.org' WHERE name='description';
UPDATE metadata SET value='osm2vectortiles' WHERE name='id';
UPDATE metadata SET value='osm2vectortiles' WHERE name='name';
UPDATE metadata SET value='2.0' WHERE name='version';
UPDATE metadata SET value='baselayer' WHERE name='type';
INSERT INTO metadata VALUES ('bounds', '-180,-85.0511,180,85.0511');
```

**Comment by stephan75** [comment]
Hi, I am watching your everyday work and efforts about this project via github watchlist ... Thanks a lot!

Will there be any announcement or blog posting when version 2 is "really" released?

Maybe wen can then report about it in

http://wiki.openstreetmap.org/wiki/Wochennotiz and 

http://wiki.openstreetmap.org/wiki/WeeklyOSM

if you want?
